name: helm
version: '2.9.1'
summary: The Kubernetes package manager
description: |
  Helm is a tool for managing Kubernetes
  charts. Charts are packages of
  pre-configured Kubernetes resources.

grade: stable
confinement: strict

apps:
  helm:
    command: helm.wrapper
    environment:
        HELM_HOME: $SNAP_USER_COMMON
        KUBECONFIG: $SNAP_USER_COMMON/kube/config
    plugs:
      - network
      - network-bind
      - home

parts:
  wrapper:
    plugin: dump
    source: .
    stage:
      - helm.wrapper
  helm:
    after:
      - wrapper
    plugin: dump
    source: https://storage.googleapis.com/kubernetes-helm/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-amd64.tar.gz
    stage:
      - helm

