name: helm
version: '2.9.1'
summary: The Kubernetes package manager
description: |
  Helm is a tool for managing Kubernetes
  charts. Charts are packages of
  pre-configured Kubernetes resources.

grade: stable
confinement: classic

apps:
  helm:
    command: helm
    plugs:
      - network
      - network-bind
      - home

parts:
  helm:
    plugin: dump
    source: https://storage.googleapis.com/kubernetes-helm/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-amd64.tar.gz
    stage:
      - helm

