name: helm
version: '2.12.0'
summary: The Kubernetes package manager
description: |
  Helm is a tool for managing Kubernetes
  charts. Charts are packages of
  pre-configured Kubernetes resources.

grade: stable
confinement: classic

apps:
  helm:
    command: helm

parts:
  helm:
    plugin: dump
    source: 
      - on amd64: https://storage.googleapis.com/kubernetes-helm/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-amd64.tar.gz
      - on i386: https://storage.googleapis.com/kubernetes-helm/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-386.tar.gz
      - on armhf: https://storage.googleapis.com/kubernetes-helm/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-arm.tar.gz
      - on arm64: https://storage.googleapis.com/kubernetes-helm/helm-v$SNAPCRAFT_PROJECT_VERSION-linux-arm64.tar.gz
    stage:
      - helm
