name: Release

on:
  # Run the workflow each time new commits are pushed to the 3 branch.
  push:
    branches: [ "3" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  get-architectures:
    name: 🖥 Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: 🖥 Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main

  release:
    name: 🚢 Release to 3/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "3 Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: 🚢 Release to 3/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          architecture: ${{ matrix.architecture }}
          channel: 3/candidate
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
  
  call-for-testing:
    name: 📣 Create call for testing
    needs: [release, get-architectures]
    environment: "3 Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: 📣 Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          channel: 3/candidate
          promotion-channel: 3/stable
          github-token: ${{ secrets.GITHUB_TOKEN }}
